package ltdjms.discord.product.domain;

import java.time.Instant;

/**
 * Domain record representing an entry in the escort option catalog.
 *
 * <p>Maps to the {@code escort_option_catalog} table. Each entry defines a type of escort service
 * with its default price (TWD). Guild-specific price overrides are stored separately in the {@code
 * guild_escort_option_price} table.
 *
 * @param id the primary key (generated by DB, null for new entries)
 * @param code the unique option code (e.g. CONF_DAM_300W)
 * @param type the order type (包本單, 小時單, 哈夫幣累積單, 特殊條件, 指定大紅)
 * @param level the service level (機密護, 絕密護, 不限)
 * @param mapScope the applicable map scope
 * @param target the target/description
 * @param priceTwd the default price in TWD (must be > 0)
 * @param createdAt the creation timestamp
 * @param updatedAt the last update timestamp
 */
public record EscortOptionCatalog(
    Long id,
    String code,
    String type,
    String level,
    String mapScope,
    String target,
    long priceTwd,
    Instant createdAt,
    Instant updatedAt) {

  /** Compact constructor with validation. */
  public EscortOptionCatalog {
    if (code == null || code.isBlank()) {
      throw new IllegalArgumentException("code must not be blank");
    }
    if (type == null || type.isBlank()) {
      throw new IllegalArgumentException("type must not be blank");
    }
    if (level == null || level.isBlank()) {
      throw new IllegalArgumentException("level must not be blank");
    }
    if (mapScope == null || mapScope.isBlank()) {
      throw new IllegalArgumentException("mapScope must not be blank");
    }
    if (target == null || target.isBlank()) {
      throw new IllegalArgumentException("target must not be blank");
    }
    if (priceTwd <= 0) {
      throw new IllegalArgumentException("priceTwd must be > 0");
    }
  }

  /**
   * Factory method for creating a new catalog entry without generated id and timestamps.
   *
   * @param code the unique option code
   * @param type the order type
   * @param level the service level
   * @param mapScope the applicable map scope
   * @param target the target/description
   * @param priceTwd the default price in TWD
   * @return a new EscortOptionCatalog with null id, null timestamps
   */
  public static EscortOptionCatalog create(
      String code, String type, String level, String mapScope, String target, long priceTwd) {
    return new EscortOptionCatalog(null, code, type, level, mapScope, target, priceTwd, null, null);
  }

  /**
   * Returns a copy with updated details, preserving the id and timestamps from the original.
   *
   * @param code the new code
   * @param type the new type
   * @param level the new level
   * @param mapScope the new map scope
   * @param target the new target
   * @param priceTwd the new price in TWD
   * @return a new EscortOptionCatalog with updated values
   */
  public EscortOptionCatalog withUpdatedDetails(
      String code, String type, String level, String mapScope, String target, long priceTwd) {
    return new EscortOptionCatalog(
        id, code, type, level, mapScope, target, priceTwd, createdAt, updatedAt);
  }
}
